/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.3.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as chat from "../chat.js";
import type * as clerk from "../clerk.js";
import type * as files from "../files.js";
import type * as http from "../http.js";
import type * as message from "../message.js";
import type * as notifications from "../notifications.js";
import type * as orders from "../orders.js";
import type * as sellerGigs from "../sellerGigs.js";
import type * as users from "../users.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  chat: typeof chat;
  clerk: typeof clerk;
  files: typeof files;
  http: typeof http;
  message: typeof message;
  notifications: typeof notifications;
  orders: typeof orders;
  sellerGigs: typeof sellerGigs;
  users: typeof users;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
