export const CONSTRUCTION_RESOURCES = [
    { name: "Cement", unit: "kg" },
    { name: "Sand", unit: "m³" },
    { name: "Gravel", unit: "m³" },
    { name: "Steel Rebar", unit: "kg" },
    { name: "Bricks", unit: "pieces" },
    { name: "Concrete Blocks", unit: "pieces" },
    { name: "Wood Planks", unit: "m²" },
    { name: "Plywood", unit: "sheets" },
    { name: "Roofing Tiles", unit: "pieces" },
    { name: "Paint", unit: "liters" },
    { name: "Insulation", unit: "m²" },
    { name: "Drywall", unit: "sheets" },
    { name: "Nails", unit: "kg" },
    { name: "Screws", unit: "boxes" },
    { name: "Electrical Wire", unit: "m" },
    { name: "PVC Pipes", unit: "m" },
    { name: "Glass Panes", unit: "m²" },
    { name: "Ceramic Tiles", unit: "m²" },
    { name: "Mortar", unit: "kg" },
    { name: "Sealant", unit: "tubes" }
  ];
  
  export const CONSTRUCTION_TOOLS = [
    { name: "Hammer", unit: "pieces" },
    { name: "Screwdriver Set", unit: "sets" },
    { name: "Power Drill", unit: "pieces" },
    { name: "Circular Saw", unit: "pieces" },
    { name: "Level", unit: "pieces" },
    { name: "Measuring Tape", unit: "pieces" },
    { name: "Wheelbarrow", unit: "pieces" },
    { name: "Shovel", unit: "pieces" },
    { name: "Trowel", unit: "pieces" },
    { name: "Paint Roller", unit: "pieces" },
    { name: "Ladder", unit: "pieces" },
    { name: "Safety Helmet", unit: "pieces" },
    { name: "Work Gloves", unit: "pairs" },
    { name: "Cement Mixer", unit: "pieces" },
    { name: "Jackhammer", unit: "pieces" },
    { name: "Scaffolding", unit: "sets" },
    { name: "Welding Machine", unit: "pieces" },
    { name: "Chainsaw", unit: "pieces" },
    { name: "Pneumatic Nailer", unit: "pieces" },
    { name: "Angle Grinder", unit: "pieces" }
  ];